### ISSUE TITLE
INCLUDES - Invalid bind expression type of List<String> for column of type String

### ISSUE THREAD

**Issue by konradbeck-creditech** [apexfarm/ApexQuery#4]
It seems the bind expression for the INCLUDES function is expecting a comma separated String instead of a List.

Example:

Query.Filter filter = Query.includes(AccountContactRelation.Roles, new List<String>{ 'AAA', 'BBB', 'CCC', 'DDD', 'EEE' });
Query.of(AccountContactRelation.SObjectType).filterBy(filter).run();

**Comment by inksword** [comment]
@konradbeck-creditech Thanks for raising this issue again. This has been fixed along with the other includes/excludes bug you have posted.
